### ISSUE TITLE
Website genix.me is down

### ISSUE THREAD

**Issue by luzpaz** [GeniXCMS/GeniXCMS#117]
**Describe the bug**

![Screenshot_20240109_213727](https://github.com/GeniXCMS/GeniXCMS/assets/4140247/d23c169d-25c4-4aa0-942d-778c1383dc56)

**Comment by semplon** [comment]
Hello @luzpaz 
Thank You for mention this. Right now we are having fund problem to renew the domain. May be We will change to new domain with low price. So we had no problem to renew every years.

**Comment by luzpaz** [comment]
Perhaps just hosting it on github,io ?

**Comment by semplon** [comment]
Yes, for hosting we can use github.io.

**Comment by semplon** [comment]
Hello @luzpaz the website is up now with new address
visit https://genixcms.my.id
docs can be accessed here https://docs.genixcms.my.id
